apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commitment-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AmanHogan/k3s
    targetRevision: HEAD
    path: manifests/commitment-tracker
  destination:
    server: https://kubernetes.default.svc
    namespace: commitment-tracker
  syncPolicy:
    automated:
      prune: true # delete resources removed from git
      selfHeal: true # revert manual kubectl changes
    syncOptions:
      - CreateNamespace=true
