apiVersion: apps/v1
kind: Deployment
metadata:
  name: commitment-tracker-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commitment-tracker-api
  template:
    metadata:
      labels:
        app: commitment-tracker-api
    spec:
      # Wait for MongoDB to accept connections before starting Spring Boot
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nc -z mongodb 27017; do echo waiting for mongodb; sleep 2; done",
            ]
      containers:
        - name: commitment-tracker-api
          image: 192.168.56.20:5001/commitment-tracker-api:9f5fda7
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: "mongodb://admin:password123@mongodb:27017/commitment_tracker?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: commitment-tracker-api
  namespace: default
spec:
  selector:
    app: commitment-tracker-api
  ports:
    - port: 8080
      targetPort: 8080
