controller:
  serviceType: LoadBalancer
  installPlugins:
    - kubernetes:latest
    - git:latest
    - workflow-aggregator:latest
    - pipeline-stage-view:latest
    - docker-workflow:latest
    - ssh-slaves:latest
    - credentials:latest
    - ssh-credentials:latest
