apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k3s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-k3s
  template:
    metadata:
      labels:
        app: hello-k3s
    spec:
      containers:
        - name: hello-k3s
          image: 192.168.56.1:5001/hello-k3s:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-k3s
spec:
  type: LoadBalancer
  selector:
    app: hello-k3s
  ports:
    - port: 80
      targetPort: 80
